language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm
  - hhvm-nightly
  - nightly

matrix:
  allow_failures:
    - php: hhvm-nightly
    - php: nightly

before_script:
  - if [[ $TRAVIS_PHP_VERSION =~ ^php ]]; then phpenv config-rm xdebug.ini; fi
  - composer selfupdate
  - composer update --no-interaction --prefer-dist

script:
  - ./vendor/phpunit/phpunit/phpunit -v
